project_id = "nuvysdrckdlakgqutyqv"

[functions.admin-reset-test-user]
verify_jwt = false

[functions.admin-reset-and-seed]
verify_jwt = false

[functions.admin-create-test-profile]
verify_jwt = false
